### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: NoSuchMethodError: The method '[]' was called on null.

### ISSUE THREAD

**Issue by SimonBurfield** [mdanics/fluttergram#113]
I have set this up in Firebase etc, and I can see 
GoogleSignInAccount user = googleSignIn.currentUser; has user information

However this function is not working

```
factory User.fromDocument(DocumentSnapshot doc) {
    return User(
      email: doc.data()['email'],
      username: doc.data()['username'],
      photoUrl: doc.data()['photoUrl'],
      id: doc.id,
      displayName: doc.data()['displayName'],
      bio: doc.data()['bio'],
      followers: doc.data()['followers'],
      following: doc.data()['following'],
    );
  }
```

```
E/flutter (28234): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: NoSuchMethodError: The method '[]' was called on null.
E/flutter (28234): Receiver: null
E/flutter (28234): Tried calling: []("email")
E/flutter (28234): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
E/flutter (28234): #1      new User.fromDocument (package:Fluttergram/models/user.dart:25:24)
E/flutter (28234): #2      tryCreateUserRecord (package:Fluttergram/main.dart:144:27)
E/flutter (28234): <asynchronous suspension>
E/flutter (28234): #3      _ensureLoggedIn (package:Fluttergram/main.dart:40:5)
E/flutter (28234): <asynchronous suspension>
E/flutter (28234): #4      _HomePageState.login (package:Fluttergram/main.dart:296:5)
E/flutter (28234): <asynchronous suspension>
E/flutter (28234): 
E/flutter (28234): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: NoSuchMethodError: The method '[]' was called on null.
E/flutter (28234): Receiver: null
E/flutter (28234): Tried calling: []("email")
E/flutter (28234): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
E/flutter (28234): #1      new User.fromDocument (package:Fluttergram/models/user.dart:25:24)
E/flutter (28234): #2      tryCreateUserRecord (package:Fluttergram/main.dart:144:27)
E/flutter (28234): <asynchronous suspension>
E/flutter (28234): #3      _silentLogin (package:Fluttergram/main.dart:63:5)
E/flutter (28234): <asynchronous suspension>
E/flutter (28234): #4      _HomePageState.silentLogin (package:Fluttergram/main.dart:310:5)
E/flutter (28234): <asynchronous suspension>
E/flutter (28234): 
```

**Comment by mdanics** [comment]
When are you getting this error? On login? Sign up?

**Comment by SimonBurfield** [comment]
Good afternoon, so when I hit the google signup button, a screen appears where I can select my google account, its after that it fails

**Comment by mdanics** [comment]
Ok, and this is the first attempt at logging in?

**Comment by SimonBurfield** [comment]
Yes it was.  I found if I commented out 

 if (userRecord.data == null) {
 }
 (just the check, not the containing code)
 
 If would ask for a username, and then work, subsequential logins would work fine

**Comment by mdanics** [comment]
Fixed in #114

**Comment by SimonBurfield** [comment]
Thank you :)

**Comment by mdanics** [comment]
Thanks to @lcw99  😃
