### ISSUE TITLE
Google signin not working. Gives the following errors:

### ISSUE THREAD

**Issue by willvlad** [mdanics/fluttergram#73]
`D/EGL_emulation( 4924): eglMakeCurrent: 0xec785ba0: ver 3 0 (tinfo 0xd2394040)
W/ActivityThread( 4924): handleWindowVisibility: no activity for token android.os.BinderProxy@1f48de5
D/EGL_emulation( 4924): eglMakeCurrent: 0xec785ba0: ver 3 0 (tinfo 0xd2394040)
E/flutter ( 4924): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null)
E/flutter ( 4924): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter ( 4924): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter ( 4924): <asynchronous suspension>
E/flutter ( 4924): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter ( 4924): #3      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:226:58)
E/flutter ( 4924): <asynchronous suspension>
E/flutter ( 4924): #4      GoogleSignIn._addMethodCall.<anonymous closure> (package:google_sign_in/google_sign_in.dart:281:28)
E/flutter ( 4924): #5      _rootRun (dart:async/zone.dart:1122:38)
E/flutter ( 4924): #6      _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter ( 4924): #7      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:164:18)
E/flutter ( 4924): #8      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:652:39)
E/flutter ( 4924): #9      Future._propagateToListeners (dart:async/future_impl.dart:708:37)
E/flutter ( 4924): #10     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:391:9)
E/flutter ( 4924): #11     _rootRun (dart:async/zone.dart:1126:13)
E/flutter ( 4924): #12     _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter ( 4924): #13     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
E/flutter ( 4924): #14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
E/flutter ( 4924): #15     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
E/flutter ( 4924): #16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
E/flutter ( 4924): `

**Comment by mdanics** [comment]
Have you correctly set up google services? See [set up the firebase app](https://github.com/mdanics/fluttergram#3-setup-the-firebase-app) in the Readme.

Let me know if you still get the error after following the steps listed there

**Comment by hlj2722** [comment]
the same problem 
-------------------------------------------------
E/flutter (14815): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null)
E/flutter (14815): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (14815): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter (14815): <asynchronous suspension>
E/flutter (14815): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:349:48)
E/flutter (14815): #3      MethodChannelGoogleSignIn.signIn (package:google_sign_in_platform_interface/src/method_channel_google_sign_in.dart:45:10)
E/flutter (14815): #4      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:227:42)
E/flutter (14815): <asynchronous suspension>
E/flutter (14815): #5      GoogleSignIn._addMethodCall.<anonymous closure> (package:google_sign_in/google_sign_in.dart:291:16)
E/flutter (14815): #6      _rootRunUnary (dart:async/zone.dart:1134:38)
E/flutter (14815): #7      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter (14815): #8      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
E/flutter (14815): #9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
E/flutter (14815): #10     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
E/flutter (14815): #11     Future._completeWithValue (dart:async/future_impl.dart:524:5)
E/flutter (14815): #12     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
E/flutter (14815): #13     _rootRun (dart:async/zone.dart:1126:13)
E/flutter (14815): #14     _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter (14815): #15     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
E/flutter (14815): #16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
E/flutter (14815): #17     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
E/flutter (14815): #18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
E/flutter (14815):

**Comment by mdanics** [comment]
@hlj2722 have you correctly set up google services as per my previous comment?

**Comment by adamdupuis** [comment]
I am also having this issue and I did set up Google Services as stated in the Instructions. I also filled out the required fields on the "Oauth consent screen" in Google Console for my Firebase project.

When clicking the "Sign in with Google" button, I choose my Google account and the prompt disappears, but nothing happens.

**Comment by saurabh-mhaisekar** [comment]
I'm facing same error. I've set up the Google Services correctly. It works fine in Debug mode but fails on release build. Any idea why?

**Comment by adamdupuis** [comment]
@SaurabhSM I believe this case means you have not added the SHA-256 certificate to your app on Firebase.

**Comment by saurabh-mhaisekar** [comment]
@adamdupuis Thanks, looks like I was referring to old fingerprint. Worked after updating to appropriate fingerprint. Appreciate your help
